### ISSUE TITLE
Question about Pod Providers vs Identity Providers

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/culture#46]
Question about the roles in the Stakeholders document.

What's the difference between Pod Providers and Identity Providers?
(And which of these do 'solid server implementations' fall under?)

**Comment by RubenVerborgh** [comment]
A pod provider provides storage, i.e., disk space where you can store files.

An identity provider provides an identity, i.e., lets you authenticate with a given WebID.

(The profile document tied to that WebID is indeed located in some storage, but that does not _have_ to be the identity provider.)

The current NSS provides both. However, it is perfectly possible for me to have my identity managed by one server and my data stored by another.

> (And which of these do 'solid server implementations' fall under?)

I would be inclined to say "pod provider". A Solid server might optionally also be an identity provider; but the main functionality is that you can read/write documents under access control.

**Comment by dmitrizagidulin** [comment]
Got it, thanks @RubenVerborgh!
