### ISSUE TITLE
WebID-TLS "Legacy Protocol" tag

### ISSUE THREAD

**Issue by kidehen** [solid/culture#55]
Solid is a multi-protocol platform. Thus, there is no need for the current "legacy tag" associated with WebID-TLS. 

WebID-TLS and WebID-OIDC are protocols supported by Solid.

**Comment by TallTed** [comment]
Fixed by #61. I think #55 can now be closed.

**Comment by justinwb** [comment]
Agree. @kidehen I'm closing this but feel free to reopen if you disagree.
